---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by raylanhong.
--- DateTime: 1/22/2025 9:55 AM
---

local EPropertyClass = import("EPropertyClass")
local ArrTest = slua.Array(EPropertyClass.Struct, import("UserInfo"))

ArrTest:Add({id = 1,})
ArrTest:Add({id = 2,})
ArrTest:Add({id = 3,})
ArrTest:Add({id = 4,})

local UserInfo

for i = 0, 3 do
    UserInfo = ArrTest:Get(i, UserInfo)
    print("GCOptimise Array", UserInfo, UserInfo.id)
end

for i = 0, 3 do
    ArrTest:Set(i, "id", i + 5)

    local TempUserInfo = ArrTest:Get(i, UserInfo)
    assert(TempUserInfo == UserInfo)
    print("GCOptimise Array Set", TempUserInfo, UserInfo.id)
end

local MapTest = slua.Map(EPropertyClass.Int, EPropertyClass.Struct, nil, import("UserInfo"))
for i = 0, 3 do
    MapTest:Add(i, {id = i})
end

for i = 0, 3 do
    UserInfo = MapTest:Get(i, UserInfo)
    print("GCOptimise Map", UserInfo, UserInfo.id)
end

for i = 0, 3 do
    MapTest:Set(i, "id", i + 5)
    UserInfo = MapTest:Get(i, UserInfo)
    if UserInfo then
        print("GCOptimise Map Set", UserInfo, UserInfo.id)
    end
end